# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/d/University/Bachelor 1/PSE/Vaccin Simulator"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/d/University/Bachelor 1/PSE/Vaccin Simulator"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/University/Bachelor 1/PSE/Vaccin Simulator/CMakeFiles" "/mnt/d/University/Bachelor 1/PSE/Vaccin Simulator//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/University/Bachelor 1/PSE/Vaccin Simulator/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SingleTests

# Build rule for target.
SingleTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SingleTests
.PHONY : SingleTests

# fast build rule for target.
SingleTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/build
.PHONY : SingleTests/fast

#=============================================================================
# Target rules for targets named Vaccimulator

# Build rule for target.
Vaccimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vaccimulator
.PHONY : Vaccimulator

# fast build rule for target.
Vaccimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/build
.PHONY : Vaccimulator/fast

#=============================================================================
# Target rules for targets named VaccimulatorTests

# Build rule for target.
VaccimulatorTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VaccimulatorTests
.PHONY : VaccimulatorTests

# fast build rule for target.
VaccimulatorTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/build
.PHONY : VaccimulatorTests/fast

src/Vaccimulator.o: src/Vaccimulator.cpp.o
.PHONY : src/Vaccimulator.o

# target to build an object file
src/Vaccimulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/Vaccimulator.cpp.o
.PHONY : src/Vaccimulator.cpp.o

src/Vaccimulator.i: src/Vaccimulator.cpp.i
.PHONY : src/Vaccimulator.i

# target to preprocess a source file
src/Vaccimulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/Vaccimulator.cpp.i
.PHONY : src/Vaccimulator.cpp.i

src/Vaccimulator.s: src/Vaccimulator.cpp.s
.PHONY : src/Vaccimulator.s

# target to generate assembly for a file
src/Vaccimulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/Vaccimulator.cpp.s
.PHONY : src/Vaccimulator.cpp.s

src/entities/Hub.o: src/entities/Hub.cpp.o
.PHONY : src/entities/Hub.o

# target to build an object file
src/entities/Hub.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Hub.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Hub.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Hub.cpp.o
.PHONY : src/entities/Hub.cpp.o

src/entities/Hub.i: src/entities/Hub.cpp.i
.PHONY : src/entities/Hub.i

# target to preprocess a source file
src/entities/Hub.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Hub.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Hub.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Hub.cpp.i
.PHONY : src/entities/Hub.cpp.i

src/entities/Hub.s: src/entities/Hub.cpp.s
.PHONY : src/entities/Hub.s

# target to generate assembly for a file
src/entities/Hub.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Hub.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Hub.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Hub.cpp.s
.PHONY : src/entities/Hub.cpp.s

src/entities/Planning.o: src/entities/Planning.cpp.o
.PHONY : src/entities/Planning.o

# target to build an object file
src/entities/Planning.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Planning.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Planning.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Planning.cpp.o
.PHONY : src/entities/Planning.cpp.o

src/entities/Planning.i: src/entities/Planning.cpp.i
.PHONY : src/entities/Planning.i

# target to preprocess a source file
src/entities/Planning.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Planning.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Planning.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Planning.cpp.i
.PHONY : src/entities/Planning.cpp.i

src/entities/Planning.s: src/entities/Planning.cpp.s
.PHONY : src/entities/Planning.s

# target to generate assembly for a file
src/entities/Planning.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Planning.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Planning.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Planning.cpp.s
.PHONY : src/entities/Planning.cpp.s

src/entities/SimulationData.o: src/entities/SimulationData.cpp.o
.PHONY : src/entities/SimulationData.o

# target to build an object file
src/entities/SimulationData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/SimulationData.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/SimulationData.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/SimulationData.cpp.o
.PHONY : src/entities/SimulationData.cpp.o

src/entities/SimulationData.i: src/entities/SimulationData.cpp.i
.PHONY : src/entities/SimulationData.i

# target to preprocess a source file
src/entities/SimulationData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/SimulationData.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/SimulationData.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/SimulationData.cpp.i
.PHONY : src/entities/SimulationData.cpp.i

src/entities/SimulationData.s: src/entities/SimulationData.cpp.s
.PHONY : src/entities/SimulationData.s

# target to generate assembly for a file
src/entities/SimulationData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/SimulationData.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/SimulationData.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/SimulationData.cpp.s
.PHONY : src/entities/SimulationData.cpp.s

src/entities/Simulator.o: src/entities/Simulator.cpp.o
.PHONY : src/entities/Simulator.o

# target to build an object file
src/entities/Simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Simulator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Simulator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Simulator.cpp.o
.PHONY : src/entities/Simulator.cpp.o

src/entities/Simulator.i: src/entities/Simulator.cpp.i
.PHONY : src/entities/Simulator.i

# target to preprocess a source file
src/entities/Simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Simulator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Simulator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Simulator.cpp.i
.PHONY : src/entities/Simulator.cpp.i

src/entities/Simulator.s: src/entities/Simulator.cpp.s
.PHONY : src/entities/Simulator.s

# target to generate assembly for a file
src/entities/Simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Simulator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Simulator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Simulator.cpp.s
.PHONY : src/entities/Simulator.cpp.s

src/entities/VaccinationCenter.o: src/entities/VaccinationCenter.cpp.o
.PHONY : src/entities/VaccinationCenter.o

# target to build an object file
src/entities/VaccinationCenter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/VaccinationCenter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/VaccinationCenter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/VaccinationCenter.cpp.o
.PHONY : src/entities/VaccinationCenter.cpp.o

src/entities/VaccinationCenter.i: src/entities/VaccinationCenter.cpp.i
.PHONY : src/entities/VaccinationCenter.i

# target to preprocess a source file
src/entities/VaccinationCenter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/VaccinationCenter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/VaccinationCenter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/VaccinationCenter.cpp.i
.PHONY : src/entities/VaccinationCenter.cpp.i

src/entities/VaccinationCenter.s: src/entities/VaccinationCenter.cpp.s
.PHONY : src/entities/VaccinationCenter.s

# target to generate assembly for a file
src/entities/VaccinationCenter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/VaccinationCenter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/VaccinationCenter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/VaccinationCenter.cpp.s
.PHONY : src/entities/VaccinationCenter.cpp.s

src/entities/Vaccine.o: src/entities/Vaccine.cpp.o
.PHONY : src/entities/Vaccine.o

# target to build an object file
src/entities/Vaccine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Vaccine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Vaccine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Vaccine.cpp.o
.PHONY : src/entities/Vaccine.cpp.o

src/entities/Vaccine.i: src/entities/Vaccine.cpp.i
.PHONY : src/entities/Vaccine.i

# target to preprocess a source file
src/entities/Vaccine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Vaccine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Vaccine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Vaccine.cpp.i
.PHONY : src/entities/Vaccine.cpp.i

src/entities/Vaccine.s: src/entities/Vaccine.cpp.s
.PHONY : src/entities/Vaccine.s

# target to generate assembly for a file
src/entities/Vaccine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/entities/Vaccine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/entities/Vaccine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/entities/Vaccine.cpp.s
.PHONY : src/entities/Vaccine.cpp.s

src/json/JArray.o: src/json/JArray.cpp.o
.PHONY : src/json/JArray.o

# target to build an object file
src/json/JArray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/json/JArray.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/json/JArray.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/json/JArray.cpp.o
.PHONY : src/json/JArray.cpp.o

src/json/JArray.i: src/json/JArray.cpp.i
.PHONY : src/json/JArray.i

# target to preprocess a source file
src/json/JArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/json/JArray.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/json/JArray.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/json/JArray.cpp.i
.PHONY : src/json/JArray.cpp.i

src/json/JArray.s: src/json/JArray.cpp.s
.PHONY : src/json/JArray.s

# target to generate assembly for a file
src/json/JArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/json/JArray.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/json/JArray.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/json/JArray.cpp.s
.PHONY : src/json/JArray.cpp.s

src/json/JObject.o: src/json/JObject.cpp.o
.PHONY : src/json/JObject.o

# target to build an object file
src/json/JObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/json/JObject.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/json/JObject.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/json/JObject.cpp.o
.PHONY : src/json/JObject.cpp.o

src/json/JObject.i: src/json/JObject.cpp.i
.PHONY : src/json/JObject.i

# target to preprocess a source file
src/json/JObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/json/JObject.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/json/JObject.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/json/JObject.cpp.i
.PHONY : src/json/JObject.cpp.i

src/json/JObject.s: src/json/JObject.cpp.s
.PHONY : src/json/JObject.s

# target to generate assembly for a file
src/json/JObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/json/JObject.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/json/JObject.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/json/JObject.cpp.s
.PHONY : src/json/JObject.cpp.s

src/json/JValue.o: src/json/JValue.cpp.o
.PHONY : src/json/JValue.o

# target to build an object file
src/json/JValue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/json/JValue.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/json/JValue.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/json/JValue.cpp.o
.PHONY : src/json/JValue.cpp.o

src/json/JValue.i: src/json/JValue.cpp.i
.PHONY : src/json/JValue.i

# target to preprocess a source file
src/json/JValue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/json/JValue.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/json/JValue.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/json/JValue.cpp.i
.PHONY : src/json/JValue.cpp.i

src/json/JValue.s: src/json/JValue.cpp.s
.PHONY : src/json/JValue.s

# target to generate assembly for a file
src/json/JValue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/json/JValue.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/json/JValue.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/json/JValue.cpp.s
.PHONY : src/json/JValue.cpp.s

src/parsing/IniExporter.o: src/parsing/IniExporter.cpp.o
.PHONY : src/parsing/IniExporter.o

# target to build an object file
src/parsing/IniExporter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/parsing/IniExporter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/parsing/IniExporter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/parsing/IniExporter.cpp.o
.PHONY : src/parsing/IniExporter.cpp.o

src/parsing/IniExporter.i: src/parsing/IniExporter.cpp.i
.PHONY : src/parsing/IniExporter.i

# target to preprocess a source file
src/parsing/IniExporter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/parsing/IniExporter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/parsing/IniExporter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/parsing/IniExporter.cpp.i
.PHONY : src/parsing/IniExporter.cpp.i

src/parsing/IniExporter.s: src/parsing/IniExporter.cpp.s
.PHONY : src/parsing/IniExporter.s

# target to generate assembly for a file
src/parsing/IniExporter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/parsing/IniExporter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/parsing/IniExporter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/parsing/IniExporter.cpp.s
.PHONY : src/parsing/IniExporter.cpp.s

src/parsing/XMLParser.o: src/parsing/XMLParser.cpp.o
.PHONY : src/parsing/XMLParser.o

# target to build an object file
src/parsing/XMLParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/parsing/XMLParser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/parsing/XMLParser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/parsing/XMLParser.cpp.o
.PHONY : src/parsing/XMLParser.cpp.o

src/parsing/XMLParser.i: src/parsing/XMLParser.cpp.i
.PHONY : src/parsing/XMLParser.i

# target to preprocess a source file
src/parsing/XMLParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/parsing/XMLParser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/parsing/XMLParser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/parsing/XMLParser.cpp.i
.PHONY : src/parsing/XMLParser.cpp.i

src/parsing/XMLParser.s: src/parsing/XMLParser.cpp.s
.PHONY : src/parsing/XMLParser.s

# target to generate assembly for a file
src/parsing/XMLParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/parsing/XMLParser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/parsing/XMLParser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/parsing/XMLParser.cpp.s
.PHONY : src/parsing/XMLParser.cpp.s

src/utilities/utils.o: src/utilities/utils.cpp.o
.PHONY : src/utilities/utils.o

# target to build an object file
src/utilities/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/utilities/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/utilities/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/utilities/utils.cpp.o
.PHONY : src/utilities/utils.cpp.o

src/utilities/utils.i: src/utilities/utils.cpp.i
.PHONY : src/utilities/utils.i

# target to preprocess a source file
src/utilities/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/utilities/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/utilities/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/utilities/utils.cpp.i
.PHONY : src/utilities/utils.cpp.i

src/utilities/utils.s: src/utilities/utils.cpp.s
.PHONY : src/utilities/utils.s

# target to generate assembly for a file
src/utilities/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/src/utilities/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/src/utilities/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/src/utilities/utils.cpp.s
.PHONY : src/utilities/utils.cpp.s

tests/SingleTests.o: tests/SingleTests.cpp.o
.PHONY : tests/SingleTests.o

# target to build an object file
tests/SingleTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tests/SingleTests.cpp.o
.PHONY : tests/SingleTests.cpp.o

tests/SingleTests.i: tests/SingleTests.cpp.i
.PHONY : tests/SingleTests.i

# target to preprocess a source file
tests/SingleTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tests/SingleTests.cpp.i
.PHONY : tests/SingleTests.cpp.i

tests/SingleTests.s: tests/SingleTests.cpp.s
.PHONY : tests/SingleTests.s

# target to generate assembly for a file
tests/SingleTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tests/SingleTests.cpp.s
.PHONY : tests/SingleTests.cpp.s

tests/TestUtils.o: tests/TestUtils.cpp.o
.PHONY : tests/TestUtils.o

# target to build an object file
tests/TestUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tests/TestUtils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tests/TestUtils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/TestUtils.cpp.o
.PHONY : tests/TestUtils.cpp.o

tests/TestUtils.i: tests/TestUtils.cpp.i
.PHONY : tests/TestUtils.i

# target to preprocess a source file
tests/TestUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tests/TestUtils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tests/TestUtils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/TestUtils.cpp.i
.PHONY : tests/TestUtils.cpp.i

tests/TestUtils.s: tests/TestUtils.cpp.s
.PHONY : tests/TestUtils.s

# target to generate assembly for a file
tests/TestUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tests/TestUtils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tests/TestUtils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/TestUtils.cpp.s
.PHONY : tests/TestUtils.cpp.s

tests/VaccimulatorTests.o: tests/VaccimulatorTests.cpp.o
.PHONY : tests/VaccimulatorTests.o

# target to build an object file
tests/VaccimulatorTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/VaccimulatorTests.cpp.o
.PHONY : tests/VaccimulatorTests.cpp.o

tests/VaccimulatorTests.i: tests/VaccimulatorTests.cpp.i
.PHONY : tests/VaccimulatorTests.i

# target to preprocess a source file
tests/VaccimulatorTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/VaccimulatorTests.cpp.i
.PHONY : tests/VaccimulatorTests.cpp.i

tests/VaccimulatorTests.s: tests/VaccimulatorTests.cpp.s
.PHONY : tests/VaccimulatorTests.s

# target to generate assembly for a file
tests/VaccimulatorTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/VaccimulatorTests.cpp.s
.PHONY : tests/VaccimulatorTests.cpp.s

tests/data/JsonTests.o: tests/data/JsonTests.cpp.o
.PHONY : tests/data/JsonTests.o

# target to build an object file
tests/data/JsonTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/JsonTests.cpp.o
.PHONY : tests/data/JsonTests.cpp.o

tests/data/JsonTests.i: tests/data/JsonTests.cpp.i
.PHONY : tests/data/JsonTests.i

# target to preprocess a source file
tests/data/JsonTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/JsonTests.cpp.i
.PHONY : tests/data/JsonTests.cpp.i

tests/data/JsonTests.s: tests/data/JsonTests.cpp.s
.PHONY : tests/data/JsonTests.s

# target to generate assembly for a file
tests/data/JsonTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/JsonTests.cpp.s
.PHONY : tests/data/JsonTests.cpp.s

tests/data/XMLParserTests.o: tests/data/XMLParserTests.cpp.o
.PHONY : tests/data/XMLParserTests.o

# target to build an object file
tests/data/XMLParserTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/XMLParserTests.cpp.o
.PHONY : tests/data/XMLParserTests.cpp.o

tests/data/XMLParserTests.i: tests/data/XMLParserTests.cpp.i
.PHONY : tests/data/XMLParserTests.i

# target to preprocess a source file
tests/data/XMLParserTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/XMLParserTests.cpp.i
.PHONY : tests/data/XMLParserTests.cpp.i

tests/data/XMLParserTests.s: tests/data/XMLParserTests.cpp.s
.PHONY : tests/data/XMLParserTests.s

# target to generate assembly for a file
tests/data/XMLParserTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/XMLParserTests.cpp.s
.PHONY : tests/data/XMLParserTests.cpp.s

tests/domain/HubTests.o: tests/domain/HubTests.cpp.o
.PHONY : tests/domain/HubTests.o

# target to build an object file
tests/domain/HubTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/HubTests.cpp.o
.PHONY : tests/domain/HubTests.cpp.o

tests/domain/HubTests.i: tests/domain/HubTests.cpp.i
.PHONY : tests/domain/HubTests.i

# target to preprocess a source file
tests/domain/HubTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/HubTests.cpp.i
.PHONY : tests/domain/HubTests.cpp.i

tests/domain/HubTests.s: tests/domain/HubTests.cpp.s
.PHONY : tests/domain/HubTests.s

# target to generate assembly for a file
tests/domain/HubTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/HubTests.cpp.s
.PHONY : tests/domain/HubTests.cpp.s

tests/domain/PlanningTests.o: tests/domain/PlanningTests.cpp.o
.PHONY : tests/domain/PlanningTests.o

# target to build an object file
tests/domain/PlanningTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/PlanningTests.cpp.o
.PHONY : tests/domain/PlanningTests.cpp.o

tests/domain/PlanningTests.i: tests/domain/PlanningTests.cpp.i
.PHONY : tests/domain/PlanningTests.i

# target to preprocess a source file
tests/domain/PlanningTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/PlanningTests.cpp.i
.PHONY : tests/domain/PlanningTests.cpp.i

tests/domain/PlanningTests.s: tests/domain/PlanningTests.cpp.s
.PHONY : tests/domain/PlanningTests.s

# target to generate assembly for a file
tests/domain/PlanningTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/PlanningTests.cpp.s
.PHONY : tests/domain/PlanningTests.cpp.s

tests/domain/VaccinationCenterTests.o: tests/domain/VaccinationCenterTests.cpp.o
.PHONY : tests/domain/VaccinationCenterTests.o

# target to build an object file
tests/domain/VaccinationCenterTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccinationCenterTests.cpp.o
.PHONY : tests/domain/VaccinationCenterTests.cpp.o

tests/domain/VaccinationCenterTests.i: tests/domain/VaccinationCenterTests.cpp.i
.PHONY : tests/domain/VaccinationCenterTests.i

# target to preprocess a source file
tests/domain/VaccinationCenterTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccinationCenterTests.cpp.i
.PHONY : tests/domain/VaccinationCenterTests.cpp.i

tests/domain/VaccinationCenterTests.s: tests/domain/VaccinationCenterTests.cpp.s
.PHONY : tests/domain/VaccinationCenterTests.s

# target to generate assembly for a file
tests/domain/VaccinationCenterTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccinationCenterTests.cpp.s
.PHONY : tests/domain/VaccinationCenterTests.cpp.s

tests/domain/VaccineTests.o: tests/domain/VaccineTests.cpp.o
.PHONY : tests/domain/VaccineTests.o

# target to build an object file
tests/domain/VaccineTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccineTests.cpp.o
.PHONY : tests/domain/VaccineTests.cpp.o

tests/domain/VaccineTests.i: tests/domain/VaccineTests.cpp.i
.PHONY : tests/domain/VaccineTests.i

# target to preprocess a source file
tests/domain/VaccineTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccineTests.cpp.i
.PHONY : tests/domain/VaccineTests.cpp.i

tests/domain/VaccineTests.s: tests/domain/VaccineTests.cpp.s
.PHONY : tests/domain/VaccineTests.s

# target to generate assembly for a file
tests/domain/VaccineTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccineTests.cpp.s
.PHONY : tests/domain/VaccineTests.cpp.s

tests/presentation/SimulatorOutputTests.o: tests/presentation/SimulatorOutputTests.cpp.o
.PHONY : tests/presentation/SimulatorOutputTests.o

# target to build an object file
tests/presentation/SimulatorOutputTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/presentation/SimulatorOutputTests.cpp.o
.PHONY : tests/presentation/SimulatorOutputTests.cpp.o

tests/presentation/SimulatorOutputTests.i: tests/presentation/SimulatorOutputTests.cpp.i
.PHONY : tests/presentation/SimulatorOutputTests.i

# target to preprocess a source file
tests/presentation/SimulatorOutputTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/presentation/SimulatorOutputTests.cpp.i
.PHONY : tests/presentation/SimulatorOutputTests.cpp.i

tests/presentation/SimulatorOutputTests.s: tests/presentation/SimulatorOutputTests.cpp.s
.PHONY : tests/presentation/SimulatorOutputTests.s

# target to generate assembly for a file
tests/presentation/SimulatorOutputTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/presentation/SimulatorOutputTests.cpp.s
.PHONY : tests/presentation/SimulatorOutputTests.cpp.s

tinyxml/tinystr.o: tinyxml/tinystr.cpp.o
.PHONY : tinyxml/tinystr.o

# target to build an object file
tinyxml/tinystr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinystr.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinystr.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinystr.cpp.o
.PHONY : tinyxml/tinystr.cpp.o

tinyxml/tinystr.i: tinyxml/tinystr.cpp.i
.PHONY : tinyxml/tinystr.i

# target to preprocess a source file
tinyxml/tinystr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinystr.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinystr.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinystr.cpp.i
.PHONY : tinyxml/tinystr.cpp.i

tinyxml/tinystr.s: tinyxml/tinystr.cpp.s
.PHONY : tinyxml/tinystr.s

# target to generate assembly for a file
tinyxml/tinystr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinystr.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinystr.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinystr.cpp.s
.PHONY : tinyxml/tinystr.cpp.s

tinyxml/tinyxml.o: tinyxml/tinyxml.cpp.o
.PHONY : tinyxml/tinyxml.o

# target to build an object file
tinyxml/tinyxml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinyxml.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxml.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxml.cpp.o
.PHONY : tinyxml/tinyxml.cpp.o

tinyxml/tinyxml.i: tinyxml/tinyxml.cpp.i
.PHONY : tinyxml/tinyxml.i

# target to preprocess a source file
tinyxml/tinyxml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinyxml.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxml.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxml.cpp.i
.PHONY : tinyxml/tinyxml.cpp.i

tinyxml/tinyxml.s: tinyxml/tinyxml.cpp.s
.PHONY : tinyxml/tinyxml.s

# target to generate assembly for a file
tinyxml/tinyxml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinyxml.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxml.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxml.cpp.s
.PHONY : tinyxml/tinyxml.cpp.s

tinyxml/tinyxmlerror.o: tinyxml/tinyxmlerror.cpp.o
.PHONY : tinyxml/tinyxmlerror.o

# target to build an object file
tinyxml/tinyxmlerror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinyxmlerror.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlerror.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlerror.cpp.o
.PHONY : tinyxml/tinyxmlerror.cpp.o

tinyxml/tinyxmlerror.i: tinyxml/tinyxmlerror.cpp.i
.PHONY : tinyxml/tinyxmlerror.i

# target to preprocess a source file
tinyxml/tinyxmlerror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinyxmlerror.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlerror.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlerror.cpp.i
.PHONY : tinyxml/tinyxmlerror.cpp.i

tinyxml/tinyxmlerror.s: tinyxml/tinyxmlerror.cpp.s
.PHONY : tinyxml/tinyxmlerror.s

# target to generate assembly for a file
tinyxml/tinyxmlerror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinyxmlerror.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlerror.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlerror.cpp.s
.PHONY : tinyxml/tinyxmlerror.cpp.s

tinyxml/tinyxmlparser.o: tinyxml/tinyxmlparser.cpp.o
.PHONY : tinyxml/tinyxmlparser.o

# target to build an object file
tinyxml/tinyxmlparser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinyxmlparser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlparser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlparser.cpp.o
.PHONY : tinyxml/tinyxmlparser.cpp.o

tinyxml/tinyxmlparser.i: tinyxml/tinyxmlparser.cpp.i
.PHONY : tinyxml/tinyxmlparser.i

# target to preprocess a source file
tinyxml/tinyxmlparser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinyxmlparser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlparser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlparser.cpp.i
.PHONY : tinyxml/tinyxmlparser.cpp.i

tinyxml/tinyxmlparser.s: tinyxml/tinyxmlparser.cpp.s
.PHONY : tinyxml/tinyxmlparser.s

# target to generate assembly for a file
tinyxml/tinyxmlparser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SingleTests.dir/build.make CMakeFiles/SingleTests.dir/tinyxml/tinyxmlparser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlparser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlparser.cpp.s
.PHONY : tinyxml/tinyxmlparser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SingleTests"
	@echo "... Vaccimulator"
	@echo "... VaccimulatorTests"
	@echo "... src/Vaccimulator.o"
	@echo "... src/Vaccimulator.i"
	@echo "... src/Vaccimulator.s"
	@echo "... src/entities/Hub.o"
	@echo "... src/entities/Hub.i"
	@echo "... src/entities/Hub.s"
	@echo "... src/entities/Planning.o"
	@echo "... src/entities/Planning.i"
	@echo "... src/entities/Planning.s"
	@echo "... src/entities/SimulationData.o"
	@echo "... src/entities/SimulationData.i"
	@echo "... src/entities/SimulationData.s"
	@echo "... src/entities/Simulator.o"
	@echo "... src/entities/Simulator.i"
	@echo "... src/entities/Simulator.s"
	@echo "... src/entities/VaccinationCenter.o"
	@echo "... src/entities/VaccinationCenter.i"
	@echo "... src/entities/VaccinationCenter.s"
	@echo "... src/entities/Vaccine.o"
	@echo "... src/entities/Vaccine.i"
	@echo "... src/entities/Vaccine.s"
	@echo "... src/json/JArray.o"
	@echo "... src/json/JArray.i"
	@echo "... src/json/JArray.s"
	@echo "... src/json/JObject.o"
	@echo "... src/json/JObject.i"
	@echo "... src/json/JObject.s"
	@echo "... src/json/JValue.o"
	@echo "... src/json/JValue.i"
	@echo "... src/json/JValue.s"
	@echo "... src/parsing/IniExporter.o"
	@echo "... src/parsing/IniExporter.i"
	@echo "... src/parsing/IniExporter.s"
	@echo "... src/parsing/XMLParser.o"
	@echo "... src/parsing/XMLParser.i"
	@echo "... src/parsing/XMLParser.s"
	@echo "... src/utilities/utils.o"
	@echo "... src/utilities/utils.i"
	@echo "... src/utilities/utils.s"
	@echo "... tests/SingleTests.o"
	@echo "... tests/SingleTests.i"
	@echo "... tests/SingleTests.s"
	@echo "... tests/TestUtils.o"
	@echo "... tests/TestUtils.i"
	@echo "... tests/TestUtils.s"
	@echo "... tests/VaccimulatorTests.o"
	@echo "... tests/VaccimulatorTests.i"
	@echo "... tests/VaccimulatorTests.s"
	@echo "... tests/data/JsonTests.o"
	@echo "... tests/data/JsonTests.i"
	@echo "... tests/data/JsonTests.s"
	@echo "... tests/data/XMLParserTests.o"
	@echo "... tests/data/XMLParserTests.i"
	@echo "... tests/data/XMLParserTests.s"
	@echo "... tests/domain/HubTests.o"
	@echo "... tests/domain/HubTests.i"
	@echo "... tests/domain/HubTests.s"
	@echo "... tests/domain/PlanningTests.o"
	@echo "... tests/domain/PlanningTests.i"
	@echo "... tests/domain/PlanningTests.s"
	@echo "... tests/domain/VaccinationCenterTests.o"
	@echo "... tests/domain/VaccinationCenterTests.i"
	@echo "... tests/domain/VaccinationCenterTests.s"
	@echo "... tests/domain/VaccineTests.o"
	@echo "... tests/domain/VaccineTests.i"
	@echo "... tests/domain/VaccineTests.s"
	@echo "... tests/presentation/SimulatorOutputTests.o"
	@echo "... tests/presentation/SimulatorOutputTests.i"
	@echo "... tests/presentation/SimulatorOutputTests.s"
	@echo "... tinyxml/tinystr.o"
	@echo "... tinyxml/tinystr.i"
	@echo "... tinyxml/tinystr.s"
	@echo "... tinyxml/tinyxml.o"
	@echo "... tinyxml/tinyxml.i"
	@echo "... tinyxml/tinyxml.s"
	@echo "... tinyxml/tinyxmlerror.o"
	@echo "... tinyxml/tinyxmlerror.i"
	@echo "... tinyxml/tinyxmlerror.s"
	@echo "... tinyxml/tinyxmlparser.o"
	@echo "... tinyxml/tinyxmlparser.i"
	@echo "... tinyxml/tinyxmlparser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

