# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#════════════════════════════════════════════=================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#════════════════════════════════════════════=================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/d/University/Bachelor 1/PSE/Vaccin Simulator"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/d/University/Bachelor 1/PSE/Vaccin Simulator"

#════════════════════════════════════════════=================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/University/Bachelor 1/PSE/Vaccin Simulator/CMakeFiles" "/mnt/d/University/Bachelor 1/PSE/Vaccin Simulator/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/University/Bachelor 1/PSE/Vaccin Simulator/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#════════════════════════════════════════════=================================
# Target rules for targets named Vaccimulator

# Build rule for target.
Vaccimulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Vaccimulator
.PHONY : Vaccimulator

# fast build rule for target.
Vaccimulator/fast:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/build
.PHONY : Vaccimulator/fast

#════════════════════════════════════════════=================================
# Target rules for targets named VaccimulatorTests

# Build rule for target.
VaccimulatorTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VaccimulatorTests
.PHONY : VaccimulatorTests

# fast build rule for target.
VaccimulatorTests/fast:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/build
.PHONY : VaccimulatorTests/fast

Vaccimulator.o: Vaccimulator.cpp.o

.PHONY : Vaccimulator.o

# target to build an object file
Vaccimulator.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/Vaccimulator.cpp.o
.PHONY : Vaccimulator.cpp.o

Vaccimulator.i: Vaccimulator.cpp.i

.PHONY : Vaccimulator.i

# target to preprocess a source file
Vaccimulator.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/Vaccimulator.cpp.i
.PHONY : Vaccimulator.cpp.i

Vaccimulator.s: Vaccimulator.cpp.s

.PHONY : Vaccimulator.s

# target to generate assembly for a file
Vaccimulator.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/Vaccimulator.cpp.s
.PHONY : Vaccimulator.cpp.s

VaccimulatorTests.o: VaccimulatorTests.cpp.o

.PHONY : VaccimulatorTests.o

# target to build an object file
VaccimulatorTests.cpp.o:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/VaccimulatorTests.cpp.o
.PHONY : VaccimulatorTests.cpp.o

VaccimulatorTests.i: VaccimulatorTests.cpp.i

.PHONY : VaccimulatorTests.i

# target to preprocess a source file
VaccimulatorTests.cpp.i:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/VaccimulatorTests.cpp.i
.PHONY : VaccimulatorTests.cpp.i

VaccimulatorTests.s: VaccimulatorTests.cpp.s

.PHONY : VaccimulatorTests.s

# target to generate assembly for a file
VaccimulatorTests.cpp.s:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/VaccimulatorTests.cpp.s
.PHONY : VaccimulatorTests.cpp.s

entities/Hub.o: entities/Hub.cpp.o

.PHONY : entities/Hub.o

# target to build an object file
entities/Hub.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Hub.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Hub.cpp.o
.PHONY : entities/Hub.cpp.o

entities/Hub.i: entities/Hub.cpp.i

.PHONY : entities/Hub.i

# target to preprocess a source file
entities/Hub.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Hub.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Hub.cpp.i
.PHONY : entities/Hub.cpp.i

entities/Hub.s: entities/Hub.cpp.s

.PHONY : entities/Hub.s

# target to generate assembly for a file
entities/Hub.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Hub.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Hub.cpp.s
.PHONY : entities/Hub.cpp.s

entities/Planning.o: entities/Planning.cpp.o

.PHONY : entities/Planning.o

# target to build an object file
entities/Planning.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Planning.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Planning.cpp.o
.PHONY : entities/Planning.cpp.o

entities/Planning.i: entities/Planning.cpp.i

.PHONY : entities/Planning.i

# target to preprocess a source file
entities/Planning.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Planning.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Planning.cpp.i
.PHONY : entities/Planning.cpp.i

entities/Planning.s: entities/Planning.cpp.s

.PHONY : entities/Planning.s

# target to generate assembly for a file
entities/Planning.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Planning.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Planning.cpp.s
.PHONY : entities/Planning.cpp.s

entities/Simulator.o: entities/Simulator.cpp.o

.PHONY : entities/Simulator.o

# target to build an object file
entities/Simulator.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Simulator.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Simulator.cpp.o
.PHONY : entities/Simulator.cpp.o

entities/Simulator.i: entities/Simulator.cpp.i

.PHONY : entities/Simulator.i

# target to preprocess a source file
entities/Simulator.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Simulator.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Simulator.cpp.i
.PHONY : entities/Simulator.cpp.i

entities/Simulator.s: entities/Simulator.cpp.s

.PHONY : entities/Simulator.s

# target to generate assembly for a file
entities/Simulator.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Simulator.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Simulator.cpp.s
.PHONY : entities/Simulator.cpp.s

entities/VaccinationCenter.o: entities/VaccinationCenter.cpp.o

.PHONY : entities/VaccinationCenter.o

# target to build an object file
entities/VaccinationCenter.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/VaccinationCenter.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/VaccinationCenter.cpp.o
.PHONY : entities/VaccinationCenter.cpp.o

entities/VaccinationCenter.i: entities/VaccinationCenter.cpp.i

.PHONY : entities/VaccinationCenter.i

# target to preprocess a source file
entities/VaccinationCenter.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/VaccinationCenter.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/VaccinationCenter.cpp.i
.PHONY : entities/VaccinationCenter.cpp.i

entities/VaccinationCenter.s: entities/VaccinationCenter.cpp.s

.PHONY : entities/VaccinationCenter.s

# target to generate assembly for a file
entities/VaccinationCenter.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/VaccinationCenter.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/VaccinationCenter.cpp.s
.PHONY : entities/VaccinationCenter.cpp.s

entities/Vaccine.o: entities/Vaccine.cpp.o

.PHONY : entities/Vaccine.o

# target to build an object file
entities/Vaccine.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Vaccine.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Vaccine.cpp.o
.PHONY : entities/Vaccine.cpp.o

entities/Vaccine.i: entities/Vaccine.cpp.i

.PHONY : entities/Vaccine.i

# target to preprocess a source file
entities/Vaccine.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Vaccine.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Vaccine.cpp.i
.PHONY : entities/Vaccine.cpp.i

entities/Vaccine.s: entities/Vaccine.cpp.s

.PHONY : entities/Vaccine.s

# target to generate assembly for a file
entities/Vaccine.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/entities/Vaccine.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/entities/Vaccine.cpp.s
.PHONY : entities/Vaccine.cpp.s

io/XMLParser.o: io/XMLParser.cpp.o

.PHONY : io/XMLParser.o

# target to build an object file
io/XMLParser.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/io/XMLParser.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/io/XMLParser.cpp.o
.PHONY : io/XMLParser.cpp.o

io/XMLParser.i: io/XMLParser.cpp.i

.PHONY : io/XMLParser.i

# target to preprocess a source file
io/XMLParser.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/io/XMLParser.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/io/XMLParser.cpp.i
.PHONY : io/XMLParser.cpp.i

io/XMLParser.s: io/XMLParser.cpp.s

.PHONY : io/XMLParser.s

# target to generate assembly for a file
io/XMLParser.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/io/XMLParser.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/io/XMLParser.cpp.s
.PHONY : io/XMLParser.cpp.s

json/JArray.o: json/JArray.cpp.o

.PHONY : json/JArray.o

# target to build an object file
json/JArray.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/json/JArray.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/json/JArray.cpp.o
.PHONY : json/JArray.cpp.o

json/JArray.i: json/JArray.cpp.i

.PHONY : json/JArray.i

# target to preprocess a source file
json/JArray.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/json/JArray.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/json/JArray.cpp.i
.PHONY : json/JArray.cpp.i

json/JArray.s: json/JArray.cpp.s

.PHONY : json/JArray.s

# target to generate assembly for a file
json/JArray.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/json/JArray.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/json/JArray.cpp.s
.PHONY : json/JArray.cpp.s

json/JObject.o: json/JObject.cpp.o

.PHONY : json/JObject.o

# target to build an object file
json/JObject.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/json/JObject.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/json/JObject.cpp.o
.PHONY : json/JObject.cpp.o

json/JObject.i: json/JObject.cpp.i

.PHONY : json/JObject.i

# target to preprocess a source file
json/JObject.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/json/JObject.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/json/JObject.cpp.i
.PHONY : json/JObject.cpp.i

json/JObject.s: json/JObject.cpp.s

.PHONY : json/JObject.s

# target to generate assembly for a file
json/JObject.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/json/JObject.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/json/JObject.cpp.s
.PHONY : json/JObject.cpp.s

json/JValue.o: json/JValue.cpp.o

.PHONY : json/JValue.o

# target to build an object file
json/JValue.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/json/JValue.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/json/JValue.cpp.o
.PHONY : json/JValue.cpp.o

json/JValue.i: json/JValue.cpp.i

.PHONY : json/JValue.i

# target to preprocess a source file
json/JValue.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/json/JValue.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/json/JValue.cpp.i
.PHONY : json/JValue.cpp.i

json/JValue.s: json/JValue.cpp.s

.PHONY : json/JValue.s

# target to generate assembly for a file
json/JValue.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/json/JValue.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/json/JValue.cpp.s
.PHONY : json/JValue.cpp.s

tests/TestUtils.o: tests/TestUtils.cpp.o

.PHONY : tests/TestUtils.o

# target to build an object file
tests/TestUtils.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tests/TestUtils.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/TestUtils.cpp.o
.PHONY : tests/TestUtils.cpp.o

tests/TestUtils.i: tests/TestUtils.cpp.i

.PHONY : tests/TestUtils.i

# target to preprocess a source file
tests/TestUtils.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tests/TestUtils.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/TestUtils.cpp.i
.PHONY : tests/TestUtils.cpp.i

tests/TestUtils.s: tests/TestUtils.cpp.s

.PHONY : tests/TestUtils.s

# target to generate assembly for a file
tests/TestUtils.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tests/TestUtils.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/TestUtils.cpp.s
.PHONY : tests/TestUtils.cpp.s

tests/data/JsonTests.o: tests/data/JsonTests.cpp.o

.PHONY : tests/data/JsonTests.o

# target to build an object file
tests/data/JsonTests.cpp.o:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/JsonTests.cpp.o
.PHONY : tests/data/JsonTests.cpp.o

tests/data/JsonTests.i: tests/data/JsonTests.cpp.i

.PHONY : tests/data/JsonTests.i

# target to preprocess a source file
tests/data/JsonTests.cpp.i:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/JsonTests.cpp.i
.PHONY : tests/data/JsonTests.cpp.i

tests/data/JsonTests.s: tests/data/JsonTests.cpp.s

.PHONY : tests/data/JsonTests.s

# target to generate assembly for a file
tests/data/JsonTests.cpp.s:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/JsonTests.cpp.s
.PHONY : tests/data/JsonTests.cpp.s

tests/data/XMLParserTests.o: tests/data/XMLParserTests.cpp.o

.PHONY : tests/data/XMLParserTests.o

# target to build an object file
tests/data/XMLParserTests.cpp.o:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/XMLParserTests.cpp.o
.PHONY : tests/data/XMLParserTests.cpp.o

tests/data/XMLParserTests.i: tests/data/XMLParserTests.cpp.i

.PHONY : tests/data/XMLParserTests.i

# target to preprocess a source file
tests/data/XMLParserTests.cpp.i:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/XMLParserTests.cpp.i
.PHONY : tests/data/XMLParserTests.cpp.i

tests/data/XMLParserTests.s: tests/data/XMLParserTests.cpp.s

.PHONY : tests/data/XMLParserTests.s

# target to generate assembly for a file
tests/data/XMLParserTests.cpp.s:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/data/XMLParserTests.cpp.s
.PHONY : tests/data/XMLParserTests.cpp.s

tests/domain/HubTests.o: tests/domain/HubTests.cpp.o

.PHONY : tests/domain/HubTests.o

# target to build an object file
tests/domain/HubTests.cpp.o:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/HubTests.cpp.o
.PHONY : tests/domain/HubTests.cpp.o

tests/domain/HubTests.i: tests/domain/HubTests.cpp.i

.PHONY : tests/domain/HubTests.i

# target to preprocess a source file
tests/domain/HubTests.cpp.i:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/HubTests.cpp.i
.PHONY : tests/domain/HubTests.cpp.i

tests/domain/HubTests.s: tests/domain/HubTests.cpp.s

.PHONY : tests/domain/HubTests.s

# target to generate assembly for a file
tests/domain/HubTests.cpp.s:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/HubTests.cpp.s
.PHONY : tests/domain/HubTests.cpp.s

tests/domain/VaccinationCenterTests.o: tests/domain/VaccinationCenterTests.cpp.o

.PHONY : tests/domain/VaccinationCenterTests.o

# target to build an object file
tests/domain/VaccinationCenterTests.cpp.o:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccinationCenterTests.cpp.o
.PHONY : tests/domain/VaccinationCenterTests.cpp.o

tests/domain/VaccinationCenterTests.i: tests/domain/VaccinationCenterTests.cpp.i

.PHONY : tests/domain/VaccinationCenterTests.i

# target to preprocess a source file
tests/domain/VaccinationCenterTests.cpp.i:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccinationCenterTests.cpp.i
.PHONY : tests/domain/VaccinationCenterTests.cpp.i

tests/domain/VaccinationCenterTests.s: tests/domain/VaccinationCenterTests.cpp.s

.PHONY : tests/domain/VaccinationCenterTests.s

# target to generate assembly for a file
tests/domain/VaccinationCenterTests.cpp.s:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccinationCenterTests.cpp.s
.PHONY : tests/domain/VaccinationCenterTests.cpp.s

tests/domain/VaccineTests.o: tests/domain/VaccineTests.cpp.o

.PHONY : tests/domain/VaccineTests.o

# target to build an object file
tests/domain/VaccineTests.cpp.o:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccineTests.cpp.o
.PHONY : tests/domain/VaccineTests.cpp.o

tests/domain/VaccineTests.i: tests/domain/VaccineTests.cpp.i

.PHONY : tests/domain/VaccineTests.i

# target to preprocess a source file
tests/domain/VaccineTests.cpp.i:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccineTests.cpp.i
.PHONY : tests/domain/VaccineTests.cpp.i

tests/domain/VaccineTests.s: tests/domain/VaccineTests.cpp.s

.PHONY : tests/domain/VaccineTests.s

# target to generate assembly for a file
tests/domain/VaccineTests.cpp.s:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/domain/VaccineTests.cpp.s
.PHONY : tests/domain/VaccineTests.cpp.s

tests/presentation/SimulationOutputTests.o: tests/presentation/SimulationOutputTests.cpp.o

.PHONY : tests/presentation/SimulationOutputTests.o

# target to build an object file
tests/presentation/SimulationOutputTests.cpp.o:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/presentation/SimulationOutputTests.cpp.o
.PHONY : tests/presentation/SimulationOutputTests.cpp.o

tests/presentation/SimulationOutputTests.i: tests/presentation/SimulationOutputTests.cpp.i

.PHONY : tests/presentation/SimulationOutputTests.i

# target to preprocess a source file
tests/presentation/SimulationOutputTests.cpp.i:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/presentation/SimulationOutputTests.cpp.i
.PHONY : tests/presentation/SimulationOutputTests.cpp.i

tests/presentation/SimulationOutputTests.s: tests/presentation/SimulationOutputTests.cpp.s

.PHONY : tests/presentation/SimulationOutputTests.s

# target to generate assembly for a file
tests/presentation/SimulationOutputTests.cpp.s:
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tests/presentation/SimulationOutputTests.cpp.s
.PHONY : tests/presentation/SimulationOutputTests.cpp.s

tinyxml/tinystr.o: tinyxml/tinystr.cpp.o

.PHONY : tinyxml/tinystr.o

# target to build an object file
tinyxml/tinystr.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinystr.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinystr.cpp.o
.PHONY : tinyxml/tinystr.cpp.o

tinyxml/tinystr.i: tinyxml/tinystr.cpp.i

.PHONY : tinyxml/tinystr.i

# target to preprocess a source file
tinyxml/tinystr.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinystr.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinystr.cpp.i
.PHONY : tinyxml/tinystr.cpp.i

tinyxml/tinystr.s: tinyxml/tinystr.cpp.s

.PHONY : tinyxml/tinystr.s

# target to generate assembly for a file
tinyxml/tinystr.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinystr.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinystr.cpp.s
.PHONY : tinyxml/tinystr.cpp.s

tinyxml/tinyxml.o: tinyxml/tinyxml.cpp.o

.PHONY : tinyxml/tinyxml.o

# target to build an object file
tinyxml/tinyxml.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxml.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxml.cpp.o
.PHONY : tinyxml/tinyxml.cpp.o

tinyxml/tinyxml.i: tinyxml/tinyxml.cpp.i

.PHONY : tinyxml/tinyxml.i

# target to preprocess a source file
tinyxml/tinyxml.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxml.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxml.cpp.i
.PHONY : tinyxml/tinyxml.cpp.i

tinyxml/tinyxml.s: tinyxml/tinyxml.cpp.s

.PHONY : tinyxml/tinyxml.s

# target to generate assembly for a file
tinyxml/tinyxml.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxml.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxml.cpp.s
.PHONY : tinyxml/tinyxml.cpp.s

tinyxml/tinyxmlerror.o: tinyxml/tinyxmlerror.cpp.o

.PHONY : tinyxml/tinyxmlerror.o

# target to build an object file
tinyxml/tinyxmlerror.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlerror.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlerror.cpp.o
.PHONY : tinyxml/tinyxmlerror.cpp.o

tinyxml/tinyxmlerror.i: tinyxml/tinyxmlerror.cpp.i

.PHONY : tinyxml/tinyxmlerror.i

# target to preprocess a source file
tinyxml/tinyxmlerror.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlerror.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlerror.cpp.i
.PHONY : tinyxml/tinyxmlerror.cpp.i

tinyxml/tinyxmlerror.s: tinyxml/tinyxmlerror.cpp.s

.PHONY : tinyxml/tinyxmlerror.s

# target to generate assembly for a file
tinyxml/tinyxmlerror.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlerror.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlerror.cpp.s
.PHONY : tinyxml/tinyxmlerror.cpp.s

tinyxml/tinyxmlparser.o: tinyxml/tinyxmlparser.cpp.o

.PHONY : tinyxml/tinyxmlparser.o

# target to build an object file
tinyxml/tinyxmlparser.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlparser.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlparser.cpp.o
.PHONY : tinyxml/tinyxmlparser.cpp.o

tinyxml/tinyxmlparser.i: tinyxml/tinyxmlparser.cpp.i

.PHONY : tinyxml/tinyxmlparser.i

# target to preprocess a source file
tinyxml/tinyxmlparser.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlparser.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlparser.cpp.i
.PHONY : tinyxml/tinyxmlparser.cpp.i

tinyxml/tinyxmlparser.s: tinyxml/tinyxmlparser.cpp.s

.PHONY : tinyxml/tinyxmlparser.s

# target to generate assembly for a file
tinyxml/tinyxmlparser.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/tinyxml/tinyxmlparser.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/tinyxml/tinyxmlparser.cpp.s
.PHONY : tinyxml/tinyxmlparser.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/utils.cpp.o
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/utils.cpp.i
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/Vaccimulator.dir/build.make CMakeFiles/Vaccimulator.dir/utils.cpp.s
	$(MAKE) -f CMakeFiles/VaccimulatorTests.dir/build.make CMakeFiles/VaccimulatorTests.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Vaccimulator"
	@echo "... VaccimulatorTests"
	@echo "... Vaccimulator.o"
	@echo "... Vaccimulator.i"
	@echo "... Vaccimulator.s"
	@echo "... VaccimulatorTests.o"
	@echo "... VaccimulatorTests.i"
	@echo "... VaccimulatorTests.s"
	@echo "... entities/Hub.o"
	@echo "... entities/Hub.i"
	@echo "... entities/Hub.s"
	@echo "... entities/Planning.o"
	@echo "... entities/Planning.i"
	@echo "... entities/Planning.s"
	@echo "... entities/Simulator.o"
	@echo "... entities/Simulator.i"
	@echo "... entities/Simulator.s"
	@echo "... entities/VaccinationCenter.o"
	@echo "... entities/VaccinationCenter.i"
	@echo "... entities/VaccinationCenter.s"
	@echo "... entities/Vaccine.o"
	@echo "... entities/Vaccine.i"
	@echo "... entities/Vaccine.s"
	@echo "... io/XMLParser.o"
	@echo "... io/XMLParser.i"
	@echo "... io/XMLParser.s"
	@echo "... json/JArray.o"
	@echo "... json/JArray.i"
	@echo "... json/JArray.s"
	@echo "... json/JObject.o"
	@echo "... json/JObject.i"
	@echo "... json/JObject.s"
	@echo "... json/JValue.o"
	@echo "... json/JValue.i"
	@echo "... json/JValue.s"
	@echo "... tests/TestUtils.o"
	@echo "... tests/TestUtils.i"
	@echo "... tests/TestUtils.s"
	@echo "... tests/data/JsonTests.o"
	@echo "... tests/data/JsonTests.i"
	@echo "... tests/data/JsonTests.s"
	@echo "... tests/data/XMLParserTests.o"
	@echo "... tests/data/XMLParserTests.i"
	@echo "... tests/data/XMLParserTests.s"
	@echo "... tests/domain/HubTests.o"
	@echo "... tests/domain/HubTests.i"
	@echo "... tests/domain/HubTests.s"
	@echo "... tests/domain/VaccinationCenterTests.o"
	@echo "... tests/domain/VaccinationCenterTests.i"
	@echo "... tests/domain/VaccinationCenterTests.s"
	@echo "... tests/domain/VaccineTests.o"
	@echo "... tests/domain/VaccineTests.i"
	@echo "... tests/domain/VaccineTests.s"
	@echo "... tests/presentation/SimulationOutputTests.o"
	@echo "... tests/presentation/SimulationOutputTests.i"
	@echo "... tests/presentation/SimulationOutputTests.s"
	@echo "... tinyxml/tinystr.o"
	@echo "... tinyxml/tinystr.i"
	@echo "... tinyxml/tinystr.s"
	@echo "... tinyxml/tinyxml.o"
	@echo "... tinyxml/tinyxml.i"
	@echo "... tinyxml/tinyxml.s"
	@echo "... tinyxml/tinyxmlerror.o"
	@echo "... tinyxml/tinyxmlerror.i"
	@echo "... tinyxml/tinyxmlerror.s"
	@echo "... tinyxml/tinyxmlparser.o"
	@echo "... tinyxml/tinyxmlparser.i"
	@echo "... tinyxml/tinyxmlparser.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#════════════════════════════════════════════=================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

