var annotated_dup =
[
    [ "std", null, [
      [ "tr1", null, [
        [ "gtest_internal", null, [
          [ "ByRef", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref.html", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref" ],
          [ "ByRef< T & >", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref_3_01_t_01_6_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref_3_01_t_01_6_01_4" ],
          [ "AddRef", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref.html", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref" ],
          [ "AddRef< T & >", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref_3_01_t_01_6_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref_3_01_t_01_6_01_4" ],
          [ "Get", "classstd_1_1tr1_1_1gtest__internal_1_1_get.html", null ],
          [ "TupleElement", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element.html", null ],
          [ "TupleElement< true, 0, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_010_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_010_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 1, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_011_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_011_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 2, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_012_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_012_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 3, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_013_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_013_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 4, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_014_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_014_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 5, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_015_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_015_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 6, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_016_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_016_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 7, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_017_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_017_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 8, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_018_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_018_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 9, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_019_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_019_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "Get< 0 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_010_01_4.html", null ],
          [ "Get< 1 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_011_01_4.html", null ],
          [ "Get< 2 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_012_01_4.html", null ],
          [ "Get< 3 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_013_01_4.html", null ],
          [ "Get< 4 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_014_01_4.html", null ],
          [ "Get< 5 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_015_01_4.html", null ],
          [ "Get< 6 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_016_01_4.html", null ],
          [ "Get< 7 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_017_01_4.html", null ],
          [ "Get< 8 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_018_01_4.html", null ],
          [ "Get< 9 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_019_01_4.html", null ],
          [ "SameSizeTuplePrefixComparator", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator.html", null ],
          [ "SameSizeTuplePrefixComparator< 0, 0 >", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_010_00_010_01_4.html", null ],
          [ "SameSizeTuplePrefixComparator< k, k >", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_01k_00_01k_01_4.html", null ]
        ] ],
        [ "tuple", "classstd_1_1tr1_1_1tuple.html", "classstd_1_1tr1_1_1tuple" ],
        [ "tuple<>", "classstd_1_1tr1_1_1tuple_3_4.html", "classstd_1_1tr1_1_1tuple_3_4" ],
        [ "tuple_size", "structstd_1_1tr1_1_1tuple__size.html", null ],
        [ "tuple_size< GTEST_0_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__0___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_1_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__1___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_2_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__2___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_3_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__3___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_4_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__4___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_5_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__5___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_6_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__6___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_7_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__7___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_8_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__8___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_9_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__9___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_element", "structstd_1_1tr1_1_1tuple__element.html", null ]
      ] ]
    ] ],
    [ "testing", null, [
      [ "internal", null, [
        [ "UniversalPrinter", "classtesting_1_1internal_1_1_universal_printer.html", null ],
        [ "UniversalPrinter< T[N]>", "classtesting_1_1internal_1_1_universal_printer_3_01_t_0f_n_0e_4.html", null ],
        [ "UniversalPrinter< T & >", "classtesting_1_1internal_1_1_universal_printer_3_01_t_01_6_01_4.html", null ],
        [ "UniversalTersePrinter", "classtesting_1_1internal_1_1_universal_terse_printer.html", null ],
        [ "UniversalTersePrinter< T & >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01_t_01_6_01_4.html", null ],
        [ "UniversalTersePrinter< T[N]>", "classtesting_1_1internal_1_1_universal_terse_printer_3_01_t_0f_n_0e_4.html", null ],
        [ "UniversalTersePrinter< const char * >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01const_01char_01_5_01_4.html", null ],
        [ "UniversalTersePrinter< char * >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01char_01_5_01_4.html", null ],
        [ "UniversalTersePrinter< wchar_t * >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01wchar__t_01_5_01_4.html", null ],
        [ "SingleFailureChecker", "classtesting_1_1internal_1_1_single_failure_checker.html", "classtesting_1_1internal_1_1_single_failure_checker" ],
        [ "HasNewFatalFailureHelper", "classtesting_1_1internal_1_1_has_new_fatal_failure_helper.html", "classtesting_1_1internal_1_1_has_new_fatal_failure_helper" ],
        [ "FormatForComparison", "classtesting_1_1internal_1_1_format_for_comparison.html", null ],
        [ "FormatForComparison< ToPrint[N], OtherOperand >", "classtesting_1_1internal_1_1_format_for_comparison_3_01_to_print_0f_n_0e_00_01_other_operand_01_4.html", null ],
        [ "EqHelper", "classtesting_1_1internal_1_1_eq_helper.html", null ],
        [ "EqHelper< true >", "classtesting_1_1internal_1_1_eq_helper_3_01true_01_4.html", null ],
        [ "AssertHelper", "classtesting_1_1internal_1_1_assert_helper.html", "classtesting_1_1internal_1_1_assert_helper" ],
        [ "FilePath", "classtesting_1_1internal_1_1_file_path.html", "classtesting_1_1internal_1_1_file_path" ],
        [ "ScopedTrace", "classtesting_1_1internal_1_1_scoped_trace.html", "classtesting_1_1internal_1_1_scoped_trace" ],
        [ "FloatingPoint", "classtesting_1_1internal_1_1_floating_point.html", "classtesting_1_1internal_1_1_floating_point" ],
        [ "TypeIdHelper", "classtesting_1_1internal_1_1_type_id_helper.html", null ],
        [ "TestFactoryBase", "classtesting_1_1internal_1_1_test_factory_base.html", "classtesting_1_1internal_1_1_test_factory_base" ],
        [ "TestFactoryImpl", "classtesting_1_1internal_1_1_test_factory_impl.html", "classtesting_1_1internal_1_1_test_factory_impl" ],
        [ "ConstCharPtr", "structtesting_1_1internal_1_1_const_char_ptr.html", "structtesting_1_1internal_1_1_const_char_ptr" ],
        [ "Random", "classtesting_1_1internal_1_1_random.html", "classtesting_1_1internal_1_1_random" ],
        [ "CompileAssertTypesEqual", "structtesting_1_1internal_1_1_compile_assert_types_equal.html", null ],
        [ "CompileAssertTypesEqual< T, T >", "structtesting_1_1internal_1_1_compile_assert_types_equal_3_01_t_00_01_t_01_4.html", null ],
        [ "RemoveReference", "structtesting_1_1internal_1_1_remove_reference.html", "structtesting_1_1internal_1_1_remove_reference" ],
        [ "RemoveReference< T & >", "structtesting_1_1internal_1_1_remove_reference_3_01_t_01_6_01_4.html", "structtesting_1_1internal_1_1_remove_reference_3_01_t_01_6_01_4" ],
        [ "RemoveConst", "structtesting_1_1internal_1_1_remove_const.html", "structtesting_1_1internal_1_1_remove_const" ],
        [ "RemoveConst< const T >", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_01_4.html", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_01_4" ],
        [ "RemoveConst< const T[N]>", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_0f_n_0e_4.html", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_0f_n_0e_4" ],
        [ "AddReference", "structtesting_1_1internal_1_1_add_reference.html", "structtesting_1_1internal_1_1_add_reference" ],
        [ "AddReference< T & >", "structtesting_1_1internal_1_1_add_reference_3_01_t_01_6_01_4.html", "structtesting_1_1internal_1_1_add_reference_3_01_t_01_6_01_4" ],
        [ "ImplicitlyConvertible", "classtesting_1_1internal_1_1_implicitly_convertible.html", null ],
        [ "IsAProtocolMessage", "structtesting_1_1internal_1_1_is_a_protocol_message.html", null ],
        [ "EnableIf", "structtesting_1_1internal_1_1_enable_if.html", null ],
        [ "EnableIf< true >", "structtesting_1_1internal_1_1_enable_if_3_01true_01_4.html", "structtesting_1_1internal_1_1_enable_if_3_01true_01_4" ],
        [ "NativeArray", "classtesting_1_1internal_1_1_native_array.html", "classtesting_1_1internal_1_1_native_array" ],
        [ "linked_ptr_internal", "classtesting_1_1internal_1_1linked__ptr__internal.html", "classtesting_1_1internal_1_1linked__ptr__internal" ],
        [ "linked_ptr", "classtesting_1_1internal_1_1linked__ptr.html", "classtesting_1_1internal_1_1linked__ptr" ],
        [ "CompileAssert", "structtesting_1_1internal_1_1_compile_assert.html", null ],
        [ "StaticAssertTypeEqHelper", "structtesting_1_1internal_1_1_static_assert_type_eq_helper.html", null ],
        [ "StaticAssertTypeEqHelper< T, T >", "structtesting_1_1internal_1_1_static_assert_type_eq_helper_3_01_t_00_01_t_01_4.html", null ],
        [ "scoped_ptr", "classtesting_1_1internal_1_1scoped__ptr.html", "classtesting_1_1internal_1_1scoped__ptr" ],
        [ "RE", "classtesting_1_1internal_1_1_r_e.html", "classtesting_1_1internal_1_1_r_e" ],
        [ "GTestLog", "classtesting_1_1internal_1_1_g_test_log.html", "classtesting_1_1internal_1_1_g_test_log" ],
        [ "Mutex", "classtesting_1_1internal_1_1_mutex.html", "classtesting_1_1internal_1_1_mutex" ],
        [ "GTestMutexLock", "classtesting_1_1internal_1_1_g_test_mutex_lock.html", "classtesting_1_1internal_1_1_g_test_mutex_lock" ],
        [ "ThreadLocal", "classtesting_1_1internal_1_1_thread_local.html", "classtesting_1_1internal_1_1_thread_local" ],
        [ "bool_constant", "structtesting_1_1internal_1_1bool__constant.html", "structtesting_1_1internal_1_1bool__constant" ],
        [ "is_pointer", "structtesting_1_1internal_1_1is__pointer.html", null ],
        [ "is_pointer< T * >", "structtesting_1_1internal_1_1is__pointer_3_01_t_01_5_01_4.html", null ],
        [ "IteratorTraits", "structtesting_1_1internal_1_1_iterator_traits.html", "structtesting_1_1internal_1_1_iterator_traits" ],
        [ "IteratorTraits< T * >", "structtesting_1_1internal_1_1_iterator_traits_3_01_t_01_5_01_4.html", "structtesting_1_1internal_1_1_iterator_traits_3_01_t_01_5_01_4" ],
        [ "IteratorTraits< const T * >", "structtesting_1_1internal_1_1_iterator_traits_3_01const_01_t_01_5_01_4.html", "structtesting_1_1internal_1_1_iterator_traits_3_01const_01_t_01_5_01_4" ],
        [ "TypeWithSize", "classtesting_1_1internal_1_1_type_with_size.html", "classtesting_1_1internal_1_1_type_with_size" ],
        [ "TypeWithSize< 4 >", "classtesting_1_1internal_1_1_type_with_size_3_014_01_4.html", "classtesting_1_1internal_1_1_type_with_size_3_014_01_4" ],
        [ "TypeWithSize< 8 >", "classtesting_1_1internal_1_1_type_with_size_3_018_01_4.html", "classtesting_1_1internal_1_1_type_with_size_3_018_01_4" ],
        [ "String", "classtesting_1_1internal_1_1_string.html", null ]
      ] ],
      [ "internal2", null, [
        [ "TypeWithoutFormatter", "classtesting_1_1internal2_1_1_type_without_formatter.html", null ],
        [ "TypeWithoutFormatter< T, kProtobuf >", "classtesting_1_1internal2_1_1_type_without_formatter_3_01_t_00_01k_protobuf_01_4.html", null ],
        [ "TypeWithoutFormatter< T, kConvertibleToInteger >", "classtesting_1_1internal2_1_1_type_without_formatter_3_01_t_00_01k_convertible_to_integer_01_4.html", null ]
      ] ],
      [ "Message", "classtesting_1_1_message.html", "classtesting_1_1_message" ],
      [ "ScopedFakeTestPartResultReporter", "classtesting_1_1_scoped_fake_test_part_result_reporter.html", "classtesting_1_1_scoped_fake_test_part_result_reporter" ],
      [ "TestPartResult", "classtesting_1_1_test_part_result.html", "classtesting_1_1_test_part_result" ],
      [ "TestPartResultArray", "classtesting_1_1_test_part_result_array.html", "classtesting_1_1_test_part_result_array" ],
      [ "TestPartResultReporterInterface", "classtesting_1_1_test_part_result_reporter_interface.html", "classtesting_1_1_test_part_result_reporter_interface" ],
      [ "AssertionResult", "classtesting_1_1_assertion_result.html", "classtesting_1_1_assertion_result" ],
      [ "Test", "classtesting_1_1_test.html", "classtesting_1_1_test" ],
      [ "TestProperty", "classtesting_1_1_test_property.html", "classtesting_1_1_test_property" ],
      [ "TestResult", "classtesting_1_1_test_result.html", "classtesting_1_1_test_result" ],
      [ "TestInfo", "classtesting_1_1_test_info.html", "classtesting_1_1_test_info" ],
      [ "TestCase", "classtesting_1_1_test_case.html", "classtesting_1_1_test_case" ],
      [ "Environment", "classtesting_1_1_environment.html", "classtesting_1_1_environment" ],
      [ "TestEventListener", "classtesting_1_1_test_event_listener.html", "classtesting_1_1_test_event_listener" ],
      [ "EmptyTestEventListener", "classtesting_1_1_empty_test_event_listener.html", "classtesting_1_1_empty_test_event_listener" ],
      [ "TestEventListeners", "classtesting_1_1_test_event_listeners.html", "classtesting_1_1_test_event_listeners" ],
      [ "UnitTest", "classtesting_1_1_unit_test.html", "classtesting_1_1_unit_test" ]
    ] ],
    [ "Hub", "class_hub.html", "class_hub" ],
    [ "HubTests", "class_hub_tests.html", "class_hub_tests" ],
    [ "JArray", "class_j_array.html", "class_j_array" ],
    [ "JObject", "class_j_object.html", "class_j_object" ],
    [ "JsonTests", "class_json_tests.html", null ],
    [ "JValue", "class_j_value.html", "class_j_value" ],
    [ "Planning", "class_planning.html", "class_planning" ],
    [ "SimulationOutputTests", "class_simulation_output_tests.html", "class_simulation_output_tests" ],
    [ "Simulator", "class_simulator.html", "class_simulator" ],
    [ "TiXmlAttribute", "class_ti_xml_attribute.html", "class_ti_xml_attribute" ],
    [ "TiXmlAttributeSet", "class_ti_xml_attribute_set.html", "class_ti_xml_attribute_set" ],
    [ "TiXmlBase", "class_ti_xml_base.html", "class_ti_xml_base" ],
    [ "TiXmlComment", "class_ti_xml_comment.html", "class_ti_xml_comment" ],
    [ "TiXmlCursor", "struct_ti_xml_cursor.html", "struct_ti_xml_cursor" ],
    [ "TiXmlDeclaration", "class_ti_xml_declaration.html", "class_ti_xml_declaration" ],
    [ "TiXmlDocument", "class_ti_xml_document.html", "class_ti_xml_document" ],
    [ "TiXmlElement", "class_ti_xml_element.html", "class_ti_xml_element" ],
    [ "TiXmlHandle", "class_ti_xml_handle.html", "class_ti_xml_handle" ],
    [ "TiXmlNode", "class_ti_xml_node.html", "class_ti_xml_node" ],
    [ "TiXmlOutStream", "class_ti_xml_out_stream.html", "class_ti_xml_out_stream" ],
    [ "TiXmlParsingData", "class_ti_xml_parsing_data.html", "class_ti_xml_parsing_data" ],
    [ "TiXmlPrinter", "class_ti_xml_printer.html", "class_ti_xml_printer" ],
    [ "TiXmlString", "class_ti_xml_string.html", "class_ti_xml_string" ],
    [ "TiXmlText", "class_ti_xml_text.html", "class_ti_xml_text" ],
    [ "TiXmlUnknown", "class_ti_xml_unknown.html", "class_ti_xml_unknown" ],
    [ "TiXmlVisitor", "class_ti_xml_visitor.html", "class_ti_xml_visitor" ],
    [ "VaccinationCenter", "class_vaccination_center.html", "class_vaccination_center" ],
    [ "VaccinationCenterTests", "class_vaccination_center_tests.html", "class_vaccination_center_tests" ],
    [ "Vaccine", "class_vaccine.html", "class_vaccine" ],
    [ "VaccineTests", "class_vaccine_tests.html", null ],
    [ "XMLParser", "class_x_m_l_parser.html", "class_x_m_l_parser" ],
    [ "XMLParserTests", "class_x_m_l_parser_tests.html", "class_x_m_l_parser_tests" ]
];